# Generated by Django 2.2.4 on 2020-11-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20201106_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Notes Taken'),
            preserve_default=False,
        ),
    ]
